changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: What's New
      labels:
        - feature
        - enhancement
    - title: Improvements
      labels:
        - improvement
        - chore
        - dependencies
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
